DatasetParam:
  dataset_dir: "/home/helios/mnt/dataset/Kitti/object/"
  image_dir_path: "training/image_2"
  pointcloud_dir_path: "training/velodyne"
  label_dir_path: "training/label_2"
  calib_dir_path: "training/calib"

ROSParam:
  pointcloud_topic: "/dataset/pointcloud"
  image_topic: "/dataset/image"
  bounding_box_topic: "/dataset/ground_truth"
  frame: "lidar"

VisParam:
  # description: 自动还是手动触发显示数据（终端按回车键触发下一帧） True or False
  auto: True
  # description: 单位（秒）
  update_time: 0.5
