DatasetParam:
  dataset_dir: "/home/helios/mnt/dataset/livox_dataset/"
  gt_file: "/home/helios/mnt/dataset/livox_dataset/livox_infos_val.pkl"
  predict_file: "/home/helios/mnt/dataset/livox_dataset/result.pkl"
  image_dir_path: "training/image_2"
  pointcloud_dir_path: "training/horizon"
  label_dir_path: "training/label_2"
  calib_dir_path: "training/calib"
  prediction_dir_path: "training/prediction"

ROSParam:
  vanilla_pointcloud_topic: "/gt/pointcloud/vanilla"
  color_pointcloud_topic: "/gt/pointcloud/color"
  img_plus_box2d_topic: "/gt/img/plus_box2d"
  img_plus_box3d_topic: "/gt/img/plus_box3d"
  box3d_topic: "/box3d_marker"
  frame: "livox_frame"

VisParam:
  # description: 自动还是手动触发显示数据（终端按回车键触发下一帧） True or False
  auto: True
  # description: 单位（秒）
  update_time: 0.1
  # description: 是否显示预测结果
  show_prediction: True
