DatasetParam:
  dataset_dir: "/home/helios/mnt/dataset/livox_dataset/"
  gt_file: "/home/helios/mnt/dataset/livox_dataset/livox_infos_val.pkl"
  predict_file: "/home/helios/mnt/dataset/livox_dataset/result.pkl"
  image_dir_path: "training/image_2"
  pointcloud_dir_path: "training/horizon"
  label_dir_path: "training/label_2"
  calib_dir_path: "training/calib"

ROSParam:
  pointcloud_topic: "/dataset/pointcloud"
  image_topic: "/dataset/image"
  bounding_box_topic: "/dataset/ground_truth"
  frame: "lidar"

VisParam:
  # description: 自动还是手动触发显示数据（终端按回车键触发下一帧） True or False
  auto: True
  # description: 单位（秒）
  update_time: 0.1
  # description: 是否显示预测结果
  show_prediction: True
