name: Upload Python Package

on:
#  push:
#    branches:
#      - master
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

permissions:
  contents: read

jobs:
  deploy:
    strategy:
      matrix:
        python_version: ['3.8']
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install build
      - name: Build package
        run: python3 -m build --wheel
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
